/**
 * Pancake v2 Extension - Content Script
 * Modified to respond to CHECK_EXTENSION with EXTENSION_LOADED
 */
!function(_){
    var E={};
    function S(e){
        if(E[e])return E[e].exports;
        var T=E[e]={i:e,l:!1,exports:{}};
        return _[e].call(T.exports,T,T.exports,S),T.l=!0,T.exports
    }
    S.m=_,S.c=E,
    S.d=function(_,E,e){S.o(_,E)||Object.defineProperty(_,E,{enumerable:!0,get:e})},
    S.r=function(_){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(_,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(_,"__esModule",{value:!0})},
    S.t=function(_,E){if(1&E&&(_=S(_)),8&E)return _;if(4&E&&"object"==typeof _&&_&&_.__esModule)return _;var e=Object.create(null);if(S.r(e),Object.defineProperty(e,"default",{enumerable:!0,value:_}),2&E&&"string"!=typeof _)for(var T in _)S.d(e,T,function(E){return _[E]}.bind(null,T));return e},
    S.n=function(_){var E=_&&_.__esModule?function(){return _.default}:function(){return _};return S.d(E,"a",E),E},
    S.o=function(_,E){return Object.prototype.hasOwnProperty.call(_,E)},
    S.p="",S(S.s=7)
}({
    7:function(_,E,S){_.exports=S(8)},
    8:function(_,E){
        var S=null,e=null;

        window.addEventListener("message",(function(_){
            if(_.source==window){
                // FIX: Respond immediately to CHECK_EXTENSION with EXTENSION_LOADED
                if(_.data.type === "CHECK_EXTENSION"){
                    console.log("[CONTENTSCRIPT] Received CHECK_EXTENSION, responding with EXTENSION_LOADED");
                    window.postMessage({type:"EXTENSION_LOADED",from:"EXTENSION"},"*");
                    return;
                }

                switch(_.data.type){
                    case"LISTEN_IG_COMMENT":
                    case"STOP_LISTEN_IG_COMMENT":
                    case"PLZ_DONT_STOP_LISTEN_IG_COMMENT_THIS_PAGE":
                    case"CHECK_EXTENSION_VERSION":
                    case"PREINITIALIZE_PAGES":
                    case"PRELOAD_DOC_IDS":
                    case"LISTEN_INBOX":
                    case"STOP_LISTEN_INBOX":
                    case"PLZ_DONT_STOP_LISTEN_INBOX_THIS_PAGE":
                    case"LISTEN_WS":
                    case"STOP_LISTEN_WS":
                    case"PLZ_DONT_STOP_LISTEN_THIS_PAGE":
                    case"REMOVE_COMMENT":
                    case"SET_ACCESS_TOKEN":
                    case"UPLOAD_INBOX_PHOTO":
                    case"REPLY_INBOX_PHOTO":
                    case"LOAD_ECOMMERCE_PRODUCT":
                    case"GET_STICKERS":
                    case"GET_PACK_STICKERS":
                    case"SEND_STICKER_COMMENT":
                    case"GET_PROFILE_INFO":
                    case"GET_PROFILE_LINK":
                    case"GET_BIRTHDAY_INFO":
                    case"SEND_COMMENT":
                    case"EDIT_COMMENT":
                    case"SEND_PRIVATE_REPLY":
                    case"INVITE_LIKE_PAGE":
                    case"MAKE_MESSENGER_LINK":
                    case"POS_SYNC_PRODUCT_TO_FBSHOP":
                    case"SYNC_PRODUCT_FROM_FBSHOP_TO_POS":
                    case"REPLY_INBOX_PRODUCT":
                    case"LOAD_FACEBOOK_MESSAGES":
                    case"GET_POST_ID_FROM_LINK":
                    case"GET_IMG_FROM_SHARED_ATTACHMENT":
                    case"BLOCK_FACEBOOK_USER":
                    case"CRAWL_LIVESTREAM_DATA":
                    case"CRAWL_POST_SHARE_DATA":
                    case"REACT_MESSAGE":
                    case"BATCH_GET_GLOBAL_ID":
                    case"UPLOAD_MEDIA_TO_PANCAKE":
                    case"CONFIG_ROUTING_APP":
                    case"CHANGE_CONV_STATUS_TO_ARCHIVED":
                    case"CACHE_PAGES_ROUTING_APP":
                    case"APPROVE_APPOINTMENT":
                    case"DENY_APPOINTMENT":
                    case"LINE:INITIALIZE_PAGE":
                    case"LINE:TURN_ON_RETRY_WEBHOOK":
                    case"LINE:GET_CONVERSATIONS":
                    case"ENABLE_FIND_THREAD_BY_USERNAME":
                    case"CREATE_APPOINTMENT":
                    case"DOWNLOAD_FILE":
                    case"WAKE_UP":
                    case"LOAD_FB_POST":
                    case"GET_BUSINESS_CONTEXT":
                    case"GET_IG_CONTACT_ID":
                    case"GET_PINABLE_PRODUCTS":
                    case"TOGGLE_PIN_PRODUCT":
                    case"CRAWL_LEAD_FORM_MSG_DETAIL":
                    case"LISTEN_WS_ZALO_OA":
                    case"STOP_LISTEN_WS_ZALO_OA":
                    case"REPLY_INBOX_FILE_ZALO_OA":
                    case"REPLY_INBOX_FILE_ZALO_OA_SUCCESS":
                    case"REPLY_INBOX_FILE_ZALO_OA_FAILURE":
                    case"VALIDATE_SEND_IGD_INBOX":
                    case"GET_FB_MSG":
                    case"GET_BUSINESS_WS_CONTEXT":
                    case"GET_GLOBAL_ID_FOR_CONV":
                        try{
                            S.postMessage(_.data)
                        }catch(E){
                            console.log("error | re-setup port",E);
                            T();
                            S.postMessage(_.data)
                        }
                }
            }
        }),!1);

        var T=function(){
            e&&clearInterval(e);
            S=chrome.runtime.connect({name:"pancake_tab"});
            console.log("setup_port",S);
            S&&(
                window.postMessage({type:"EXTENSION_LOADED",from:"EXTENSION"},"*"),
                e=setInterval((function(){
                    try{
                        S.postMessage({type:"WAKE_UP"})
                    }catch(_){
                        clearInterval(e)
                    }
                }),1e4)
            );
            S.onMessage.addListener((function(_){
                switch(_.type){
                    case"I_WANT_STOP_LISTEN_IG_COMMENT":
                    case"EXTENSION_NOTIFICATIONS":
                    case"SEND_COMMENT_SUCCESS":
                    case"SEND_COMMENT_FAILURE":
                    case"I_WANT_STOP_LISTEN_INBOX":
                    case"I_WANT_STOP_LISTEN":
                    case"EXTENSION_VERSION":
                    case"REPORT_EXTENSION_STATUS":
                    case"UPLOAD_INBOX_PHOTO_SUCCESS":
                    case"UPLOAD_INBOX_PHOTO_FAILURE":
                    case"REPLY_INBOX_PHOTO_SUCCESS":
                    case"REPLY_INBOX_PHOTO_FAILURE":
                    case"REPLY_INBOX_PRODUCT_SUCCESS":
                    case"REPLY_INBOX_PRODUCT_FAILURE":
                    case"GET_STICKERS_SUCCESS":
                    case"GET_STICKERS_FAILURE":
                    case"GET_PACK_STICKERS_SUCCESS":
                    case"GET_PACK_STICKERS_FAILURE":
                    case"SEND_STICKER_COMMENT_SUCCESS":
                    case"SEND_STICKER_COMMENT_FAILURE":
                    case"GET_PROFILE_INFO_SUCCESS":
                    case"GET_PROFILE_INFO_FAILURE":
                    case"GET_PROFILE_LINK_SUCCESS":
                    case"GET_PROFILE_LINK_FAILURE":
                    case"GET_BIRTHDAY_INFO_SUCCESS":
                    case"GET_BIRTHDAY_INFO_FAILURE":
                    case"SEND_PRIVATE_REPLY_SUCCESS":
                    case"SEND_PRIVATE_REPLY_FAILURE":
                    case"REMOVE_COMMENT_SUCCESS":
                    case"REMOVE_COMMENT_FAILURE":
                    case"INVITE_LIKE_PAGE_START":
                    case"INVITE_LIKE_PAGE_PROGRESS":
                    case"INVITE_LIKE_PAGE_END":
                    case"GET_POST_ID_FROM_LINK_SUCCESS":
                    case"GET_POST_ID_FROM_LINK_FAILURE":
                    case"GET_IMG_FROM_SHARED_ATTACHMENT_SUCCESS":
                    case"GET_IMG_FROM_SHARED_ATTACHMENT_FAILURE":
                    case"MAKE_MESSENGER_LINK_SUCCESS":
                    case"SYNC_PRODUCT_FBSHOP_CACHE_PARAMS":
                    case"POS_SYNC_PRODUCT_ERROR":
                    case"POS_SYNC_PRODUCT_SUCCESS":
                    case"POS_SYNC_PRODUCT_FINISH":
                    case"MAKE_MESSENGER_LINK_FAILURE":
                    case"LOAD_FACEBOOK_MESSAGES_SUCCESS":
                    case"LOAD_FACEBOOK_MESSAGES_FAILURE":
                    case"CRAWL_LIVESTREAM_DATA_SUCCESS":
                    case"CRAWL_LIVESTREAM_DATA_FAILURE":
                    case"CRAWL_POST_SHARE_DATA_SUCCESS":
                    case"CRAWL_POST_SHARE_DATA_FAILURE":
                    case"REACT_MESSAGE_SUCCESS":
                    case"REACT_MESSAGE_FAILURE":
                    case"BLOCK_FACEBOOK_USER_SUCCESS":
                    case"BLOCK_FACEBOOK_USER_FAILURE":
                    case"BATCH_GET_GLOBAL_ID_SUCCESS":
                    case"BATCH_GET_GLOBAL_ID_FAILURE":
                    case"UPLOAD_MEDIA_TO_PANCAKE_SUCCESS":
                    case"CONFIG_ROUTING_APP_SUCCESS":
                    case"CHANGE_CONV_STATUS_TO_ARCHIVED_SUCCESS":
                    case"CHANGE_CONV_STATUS_TO_ARCHIVED_FAILURE":
                    case"CACHE_PAGES_ROUTING_APP_SUCCESS":
                    case"LINE:INITIALIZE_PAGE_SUCCESS":
                    case"LINE:TURN_ON_RETRY_WEBHOOK_SUCCESS":
                    case"LINE:INITIALIZE_PAGE_FAILURE":
                    case"LINE:GET_CONVERSATIONS_SUCCESS":
                    case"APPROVE_APPOINTMENT_SUCCESS":
                    case"APPROVE_APPOINTMENT_FAILURE":
                    case"DENY_APPOINTMENT_SUCCESS":
                    case"DENY_APPOINTMENT_FAILURE":
                    case"LINE:GET_CONVERSATIONS_FAILURE":
                    case"ENABLE_FIND_THREAD_BY_USERNAME_DONE":
                    case"LOAD_FB_POST_FAILURE":
                    case"LOAD_FB_POST_SUCCESS":
                    case"GET_BUSINESS_CONTEXT_FAILURE":
                    case"GET_BUSINESS_CONTEXT_SUCCESS":
                    case"GET_PINABLE_PRODUCTS_SUCCESS":
                    case"GET_PINABLE_PRODUCTS_FAILURE":
                    case"TOGGLE_PIN_PRODUCT_SUCCESS":
                    case"TOGGLE_PIN_PRODUCT_FAILURE":
                    case"GET_IG_CONTACT_ID_FAILURE":
                    case"GET_IG_CONTACT_ID_SUCCESS":
                    case"EDIT_COMMENT_FAILURE":
                    case"EDIT_COMMENT_SUCCESS":
                    case"DOWNLOAD_FILE_SUCCESS":
                    case"CRAWL_LEAD_FORM_MSG_DETAIL_SUCCESS":
                    case"CRAWL_LEAD_FORM_MSG_DETAIL_FAILURE":
                    case"REPLY_INBOX_FILE_ZALO_OA_SUCCESS":
                    case"REPLY_INBOX_FILE_ZALO_OA_FAILURE":
                    case"VALIDATE_SEND_IGD_INBOX_SUCCESS":
                    case"VALIDATE_SEND_IGD_INBOX_FAILURE":
                    case"GET_FB_MSG_SUCCESS":
                    case"GET_FB_MSG_FAILURE":
                    case"GET_BUSINESS_WS_CONTEXT_SUCCESS":
                    case"GET_BUSINESS_WS_CONTEXT_FAILURE":
                    case"GET_GLOBAL_ID_FOR_CONV_SUCCESS":
                    case"GET_GLOBAL_ID_FOR_CONV_FAILURE":
                        window.postMessage(_,"*")
                }
            }))
        };
        T()
    }
});
