// All message types supported by N2Store Extension
export const MSG = {
  // === Facebook Core (P0) ===
  REPLY_INBOX_PHOTO: 'REPLY_INBOX_PHOTO',
  UPLOAD_INBOX_PHOTO: 'UPLOAD_INBOX_PHOTO',
  PREINITIALIZE_PAGES: 'PREINITIALIZE_PAGES',
  GET_BUSINESS_CONTEXT: 'GET_BUSINESS_CONTEXT',
  GET_GLOBAL_ID_FOR_CONV: 'GET_GLOBAL_ID_FOR_CONV',
  CHECK_EXTENSION_VERSION: 'CHECK_EXTENSION_VERSION',
  WAKE_UP: 'WAKE_UP',

  // === Facebook Comments (P1) ===
  SEND_COMMENT: 'SEND_COMMENT',
  EDIT_COMMENT: 'EDIT_COMMENT',
  REMOVE_COMMENT: 'REMOVE_COMMENT',
  SEND_PRIVATE_REPLY: 'SEND_PRIVATE_REPLY',

  // === Facebook Interactions (P2) ===
  REACT_MESSAGE: 'REACT_MESSAGE',
  BLOCK_FACEBOOK_USER: 'BLOCK_FACEBOOK_USER',
  CHANGE_CONV_STATUS_TO_ARCHIVED: 'CHANGE_CONV_STATUS_TO_ARCHIVED',
  GET_PROFILE_INFO: 'GET_PROFILE_INFO',
  GET_PROFILE_LINK: 'GET_PROFILE_LINK',
  GET_BIRTHDAY_INFO: 'GET_BIRTHDAY_INFO',
  GET_POST_ID_FROM_LINK: 'GET_POST_ID_FROM_LINK',
  GET_IMG_FROM_SHARED_ATTACHMENT: 'GET_IMG_FROM_SHARED_ATTACHMENT',
  LOAD_FACEBOOK_MESSAGES: 'LOAD_FACEBOOK_MESSAGES',
  LOAD_FB_POST: 'LOAD_FB_POST',
  GET_FB_MSG: 'GET_FB_MSG',
  MAKE_MESSENGER_LINK: 'MAKE_MESSENGER_LINK',
  DOWNLOAD_FILE: 'DOWNLOAD_FILE',
  REPLY_INBOX_PRODUCT: 'REPLY_INBOX_PRODUCT',
  INVITE_LIKE_PAGE: 'INVITE_LIKE_PAGE',
  GET_STICKERS: 'GET_STICKERS',
  GET_PACK_STICKERS: 'GET_PACK_STICKERS',
  BATCH_GET_GLOBAL_ID: 'BATCH_GET_GLOBAL_ID',

  // === Responses ===
  EXTENSION_LOADED: 'EXTENSION_LOADED',
  EXTENSION_VERSION: 'EXTENSION_VERSION',
  EXTENSION_NOTIFICATIONS: 'EXTENSION_NOTIFICATIONS',
  REPORT_EXTENSION_STATUS: 'REPORT_EXTENSION_STATUS',
};

// Inbound message types (page → extension)
export const INBOUND_TYPES = new Set([
  MSG.REPLY_INBOX_PHOTO,
  MSG.UPLOAD_INBOX_PHOTO,
  MSG.PREINITIALIZE_PAGES,
  MSG.GET_BUSINESS_CONTEXT,
  MSG.GET_GLOBAL_ID_FOR_CONV,
  MSG.CHECK_EXTENSION_VERSION,
  MSG.WAKE_UP,
  MSG.SEND_COMMENT,
  MSG.EDIT_COMMENT,
  MSG.REMOVE_COMMENT,
  MSG.SEND_PRIVATE_REPLY,
  MSG.REACT_MESSAGE,
  MSG.BLOCK_FACEBOOK_USER,
  MSG.CHANGE_CONV_STATUS_TO_ARCHIVED,
  MSG.GET_PROFILE_INFO,
  MSG.GET_PROFILE_LINK,
  MSG.GET_BIRTHDAY_INFO,
  MSG.GET_POST_ID_FROM_LINK,
  MSG.GET_IMG_FROM_SHARED_ATTACHMENT,
  MSG.LOAD_FACEBOOK_MESSAGES,
  MSG.LOAD_FB_POST,
  MSG.GET_FB_MSG,
  MSG.MAKE_MESSENGER_LINK,
  MSG.DOWNLOAD_FILE,
  MSG.REPLY_INBOX_PRODUCT,
  MSG.INVITE_LIKE_PAGE,
  MSG.GET_STICKERS,
  MSG.GET_PACK_STICKERS,
  MSG.BATCH_GET_GLOBAL_ID,
]);

// Outbound message types (extension → page)
export const OUTBOUND_TYPES = new Set([
  MSG.EXTENSION_LOADED,
  MSG.EXTENSION_VERSION,
  MSG.EXTENSION_NOTIFICATIONS,
  MSG.REPORT_EXTENSION_STATUS,
  // Dynamic: *_SUCCESS, *_FAILURE patterns
  'REPLY_INBOX_PHOTO_SUCCESS', 'REPLY_INBOX_PHOTO_FAILURE',
  'UPLOAD_INBOX_PHOTO_SUCCESS', 'UPLOAD_INBOX_PHOTO_FAILURE',
  'SEND_COMMENT_SUCCESS', 'SEND_COMMENT_FAILURE',
  'EDIT_COMMENT_SUCCESS', 'EDIT_COMMENT_FAILURE',
  'REMOVE_COMMENT_SUCCESS', 'REMOVE_COMMENT_FAILURE',
  'SEND_PRIVATE_REPLY_SUCCESS', 'SEND_PRIVATE_REPLY_FAILURE',
  'GET_GLOBAL_ID_FOR_CONV_SUCCESS', 'GET_GLOBAL_ID_FOR_CONV_FAILURE',
  'GET_BUSINESS_CONTEXT_SUCCESS', 'GET_BUSINESS_CONTEXT_FAILURE',
  'GET_PROFILE_INFO_SUCCESS', 'GET_PROFILE_INFO_FAILURE',
  'GET_PROFILE_LINK_SUCCESS', 'GET_PROFILE_LINK_FAILURE',
  'GET_BIRTHDAY_INFO_SUCCESS', 'GET_BIRTHDAY_INFO_FAILURE',
  'GET_POST_ID_FROM_LINK_SUCCESS', 'GET_POST_ID_FROM_LINK_FAILURE',
  'GET_IMG_FROM_SHARED_ATTACHMENT_SUCCESS', 'GET_IMG_FROM_SHARED_ATTACHMENT_FAILURE',
  'LOAD_FACEBOOK_MESSAGES_SUCCESS', 'LOAD_FACEBOOK_MESSAGES_FAILURE',
  'LOAD_FB_POST_SUCCESS', 'LOAD_FB_POST_FAILURE',
  'GET_FB_MSG_SUCCESS', 'GET_FB_MSG_FAILURE',
  'MAKE_MESSENGER_LINK_SUCCESS', 'MAKE_MESSENGER_LINK_FAILURE',
  'REACT_MESSAGE_SUCCESS', 'REACT_MESSAGE_FAILURE',
  'BLOCK_FACEBOOK_USER_SUCCESS', 'BLOCK_FACEBOOK_USER_FAILURE',
  'CHANGE_CONV_STATUS_TO_ARCHIVED_SUCCESS', 'CHANGE_CONV_STATUS_TO_ARCHIVED_FAILURE',
  'DOWNLOAD_FILE_SUCCESS', 'DOWNLOAD_FILE_FAILURE',
  'BATCH_GET_GLOBAL_ID_SUCCESS', 'BATCH_GET_GLOBAL_ID_FAILURE',
  'INVITE_LIKE_PAGE_START', 'INVITE_LIKE_PAGE_PROGRESS', 'INVITE_LIKE_PAGE_END',
  'REPLY_INBOX_PRODUCT_SUCCESS', 'REPLY_INBOX_PRODUCT_FAILURE',
  'GET_STICKERS_SUCCESS', 'GET_STICKERS_FAILURE',
  'GET_PACK_STICKERS_SUCCESS', 'GET_PACK_STICKERS_FAILURE',
]);

// Valid attachment types for REPLY_INBOX_PHOTO
export const ATTACHMENT_TYPES = [
  'SEND_TEXT_ONLY',
  'PHOTO',
  'VIDEO',
  'FILE',
  'STICKER',
  'AUDIO',
  'REPLY_MESSAGE',
];

// Facebook error codes
export const FB_ERRORS = {
  WINDOW_24H: { code: 10, subcode: 2018278 },
  USER_UNAVAILABLE: { code: 551, subcode: 1545041 },
  BLOCKED_RETRY_SOCKET: { subcode: 1545012 },
  UPLOAD_BLOCKED: { subcode: 1545006 },
  RATE_LIMITED: { subcode: 3252001 },
  TEMPORARY_ERROR: { subcode: 1390008 },
};

// Extension version
export const VERSION = '1.0.0';
export const BUILD = 1;
