/* =====================================================
   SHARED LAYOUT - Orders Report System
   Injects sidebar + tab navigation into each page
   ===================================================== */

// Tab Configuration
const TAB_CONFIG = [
    {
        id: 'orders',
        href: 'tab1-orders.html',
        icon: 'shopping-cart',
        text: 'Quản Lý Đơn Hàng'
    },
    {
        id: 'statistics',
        href: 'tab2-statistics.html',
        icon: 'bar-chart-3',
        text: 'Thống Kê'
    },
    {
        id: 'upload',
        href: 'tab-upload-tpos.html',
        icon: 'upload',
        text: 'Upload Đơn Hàng Lên TPOS'
    },
    {
        id: 'product-assignment',
        href: 'tab3-product-assignment.html',
        icon: 'link',
        text: 'Gán Sản Phẩm - STT'
    }
];

// Determine current tab based on URL
function getCurrentTab() {
    const path = window.location.pathname;
    const filename = path.split('/').pop();

    if (filename.includes('tab1-orders')) return 'orders';
    if (filename.includes('tab2-statistics')) return 'statistics';
    if (filename.includes('tab-upload-tpos')) return 'upload';
    if (filename.includes('tab3-product-assignment')) return 'product-assignment';

    return 'orders'; // default
}

// Initialize layout
function initSharedLayout() {
    const currentTab = getCurrentTab();

    // Inject CSS
    injectLayoutCSS();

    // Inject sidebar
    injectSidebar();

    // Inject tab navigation
    injectTabNavigation(currentTab);

    // Initialize Lucide icons
    if (typeof lucide !== 'undefined') {
        lucide.createIcons();
    }

    // Setup event listeners
    setupLayoutEventListeners();

    // Load user info
    loadUserInfo();
}

// Inject Layout CSS
function injectLayoutCSS() {
    const style = document.createElement('style');
    style.textContent = `
        /* Layout Structure */
        body {
            margin: 0;
            padding: 0;
            display: flex;
            min-height: 100vh;
            background: var(--gray-50, #f9fafb);
        }

        /* Wrapper for content */
        .page-wrapper {
            display: flex;
            width: 100%;
        }

        .content-wrapper {
            flex: 1;
            display: flex;
            flex-direction: column;
            margin-left: 280px;
            transition: margin-left 0.3s ease;
        }

        .sidebar.collapsed + .content-wrapper {
            margin-left: 70px;
        }

        /* Tab Navigation */
        .tab-navigation {
            background: white;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
            position: sticky;
            top: 0;
            z-index: 100;
        }

        .tab-nav-content {
            display: flex;
            gap: 0;
            padding: 0 var(--spacing-xl, 2rem);
        }

        .tab-button {
            padding: 16px 24px;
            background: none;
            border: none;
            color: var(--text-secondary, #6b7280);
            font-size: 15px;
            font-weight: 500;
            cursor: pointer;
            position: relative;
            transition: all 0.2s;
            display: flex;
            align-items: center;
            gap: 8px;
            text-decoration: none;
        }

        .tab-button:hover {
            color: var(--primary, #6366f1);
            background: var(--gray-50, #f9fafb);
        }

        .tab-button.active {
            color: var(--primary, #6366f1);
        }

        .tab-button.active::after {
            content: "";
            position: absolute;
            bottom: 0;
            left: 0;
            right: 0;
            height: 3px;
            background: linear-gradient(90deg, #667eea 0%, #764ba2 100%);
            border-radius: 3px 3px 0 0;
        }

        .tab-icon {
            width: 18px;
            height: 18px;
        }

        /* Main content area */
        .main-content-area {
            flex: 1;
            overflow-y: auto;
        }
    `;
    document.head.appendChild(style);
}

// Inject Sidebar
function injectSidebar() {
    const sidebarHTML = `
        <aside class="sidebar" id="sidebar">
            <div class="sidebar-header">
                <div class="logo">
                    <i data-lucide="zap"></i>
                    <span>N2Shop</span>
                </div>
                <button class="sidebar-toggle" id="sidebarToggle">
                    <i data-lucide="panel-left-close"></i>
                </button>
            </div>

            <nav class="sidebar-nav" id="sidebarNav">
                <!-- Menu items auto-generated by navigation-modern.js -->
            </nav>

            <div class="sidebar-footer">
                <div class="user-info">
                    <div class="user-avatar">
                        <i data-lucide="user-circle"></i>
                    </div>
                    <div class="user-details">
                        <div class="user-name" id="userName">Admin</div>
                        <div class="user-role">Quản trị viên</div>
                    </div>
                </div>
                <button class="btn-logout" id="btnLogout">
                    <i data-lucide="log-out"></i>
                    <span>Đăng xuất</span>
                </button>
            </div>
        </aside>
    `;

    document.body.insertAdjacentHTML('afterbegin', sidebarHTML);
}

// Inject Tab Navigation
function injectTabNavigation(currentTab) {
    const tabButtons = TAB_CONFIG.map(tab => {
        const isActive = tab.id === currentTab ? 'active' : '';
        return `
            <a href="${tab.href}" class="tab-button ${isActive}" data-tab="${tab.id}">
                <i data-lucide="${tab.icon}" class="tab-icon"></i>
                ${tab.text}
            </a>
        `;
    }).join('');

    const navHTML = `
        <div class="tab-navigation">
            <div class="tab-nav-content">
                ${tabButtons}
            </div>
        </div>
    `;

    // Find or create content wrapper
    let contentWrapper = document.querySelector('.content-wrapper');
    if (!contentWrapper) {
        // Wrap existing body content
        const bodyContent = Array.from(document.body.children);
        contentWrapper = document.createElement('div');
        contentWrapper.className = 'content-wrapper';
        document.body.appendChild(contentWrapper);

        // Move all children except sidebar to content wrapper
        bodyContent.forEach(child => {
            if (!child.classList.contains('sidebar')) {
                contentWrapper.appendChild(child);
            }
        });
    }

    // Insert tab navigation at the beginning of content wrapper
    contentWrapper.insertAdjacentHTML('afterbegin', navHTML);
}

// Setup Event Listeners
function setupLayoutEventListeners() {
    // Sidebar toggle
    const sidebarToggle = document.getElementById('sidebarToggle');
    const sidebar = document.getElementById('sidebar');

    if (sidebarToggle && sidebar) {
        sidebarToggle.addEventListener('click', () => {
            sidebar.classList.toggle('collapsed');
            if (typeof lucide !== 'undefined') {
                setTimeout(() => lucide.createIcons(), 100);
            }
        });
    }

    // Logout handler
    const btnLogout = document.getElementById('btnLogout');
    if (btnLogout) {
        btnLogout.addEventListener('click', function() {
            if (confirm('Bạn có chắc muốn đăng xuất?')) {
                localStorage.clear();
                sessionStorage.clear();
                window.location.href = '../index.html';
            }
        });
    }
}

// Load User Info
function loadUserInfo() {
    try {
        const authData = sessionStorage.getItem('loginindex_auth') ||
                        localStorage.getItem('loginindex_auth');
        if (authData) {
            const auth = JSON.parse(authData);
            const userNameEl = document.getElementById('userName');
            if (auth.userType && userNameEl) {
                userNameEl.textContent = auth.userType.split('-')[0];
            }
        }
    } catch (error) {
        console.error('Error loading user info:', error);
    }
}

// Auto-initialize when DOM is ready
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initSharedLayout);
} else {
    initSharedLayout();
}
