#!/usr/bin/env bash
# #Note: Đọc CLAUDE.md, MEMORY.md, docs/dev-log.md trước khi code. Cập nhật dev-log sau thay đổi.
#
# Pack the full "Web 2.0" surface into a self-contained folder so the user
# can copy it as a separate deployment (GitHub Pages, Cloudflare Pages,
# Netlify, S3, plain nginx, etc.) without dragging the rest of n2store.
#
# Usage:
#   bash scripts/pack-web2.sh [output_dir]
#
# Default output: dist/web2-bundle/
#
# What's bundled (in this exact layout, so all relative paths keep working):
#   web2/                — main TPOS-clone module pages
#   web2-products/       — products page
#   web2-shared/         — shared library (sidebar, popup, page-builder)
#   native-orders/       — Đơn Web list + bulk PBH flow
#   tpos-pancake/        — TPOS × Pancake comments page
#   shared/              — common library (auth, cache, Firebase, utils)
#
# What's NOT bundled (intentional — external):
#   - Firebase SDK (loaded via CDN https://www.gstatic.com/firebasejs/...)
#   - Lucide icons (loaded via CDN https://unpkg.com/lucide@…)
#   - Cloudflare Worker proxy   (chatomni-proxy.nhijudyshop.workers.dev)
#   - Render API server         (n2store-fallback.onrender.com)
#   These are configured per-deployment — see README in the bundle for how
#   to point at your own Worker/Render instance.

set -euo pipefail

OUT_DIR="${1:-dist/web2-bundle}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

echo "[pack-web2] Source : $ROOT"
echo "[pack-web2] Output : $ROOT/$OUT_DIR"
echo

# Fresh start so old artifacts don't linger.
rm -rf "$ROOT/$OUT_DIR"
mkdir -p "$ROOT/$OUT_DIR"

# Top-level Web 2.0 folders (relative paths inside these stay intact).
WEB2_FOLDERS=(
    "web2"
    "web2-products"
    "web2-shared"
    "native-orders"
    "tpos-pancake"
)

# Copy each Web 2.0 folder verbatim.
for d in "${WEB2_FOLDERS[@]}"; do
    if [ -d "$ROOT/$d" ]; then
        echo "[pack-web2] Copying $d/ ..."
        cp -R "$ROOT/$d" "$ROOT/$OUT_DIR/"
    else
        echo "[pack-web2] WARN: $d/ missing — skipped"
    fi
done

# Bundle the common /shared/ library (browser + universal subsets only;
# /shared/node/ is server-side and not needed in the deployable bundle).
echo "[pack-web2] Copying shared/ (browser subset) ..."
mkdir -p "$ROOT/$OUT_DIR/shared"
for sub in js browser css esm images universal; do
    if [ -d "$ROOT/shared/$sub" ]; then
        cp -R "$ROOT/shared/$sub" "$ROOT/$OUT_DIR/shared/"
    fi
done
# Preserve the shared README for docs traceability
[ -f "$ROOT/shared/README.md" ] && cp "$ROOT/shared/README.md" "$ROOT/$OUT_DIR/shared/"

# Strip nothing else — relative paths inside the copied folders already
# point at ../shared/... or ../../shared/... which now resolve correctly
# inside the bundle because shared/ sits next to the Web 2.0 folders.

# Drop a small landing index so opening the bundle root makes sense.
cat > "$ROOT/$OUT_DIR/index.html" <<'LANDING'
<!-- #Note: Đọc CLAUDE.md, MEMORY.md, docs/dev-log.md trước khi code. Cập nhật dev-log sau thay đổi. -->
<!doctype html>
<html lang="vi">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="0; url=native-orders/index.html" />
        <title>Web 2.0 — N2Store bundle</title>
    </head>
    <body>
        <p>Đang chuyển tới <a href="native-orders/index.html">Đơn Web</a>…</p>
    </body>
</html>
LANDING

# Bundle README explaining what this is + how to deploy.
cat > "$ROOT/$OUT_DIR/README.md" <<'README'
# Web 2.0 — N2Store bundle

Self-contained snapshot of the Web 2.0 surface, ready to be deployed as a
separate static site. Generated by [`scripts/pack-web2.sh`](../../scripts/pack-web2.sh).

## Layout

```
web2-bundle/
├── index.html              → redirects to native-orders/
├── README.md               → this file
├── web2/                   → main TPOS-clone module pages (~80 sub-routes)
├── web2-products/          → kho sản phẩm
├── web2-shared/            → sidebar, popup, page-builder, delivery picker
├── native-orders/          → Đơn Web list + Tạo PBH flow
├── tpos-pancake/           → TPOS × Pancake comments page
└── shared/                 → common library (auth, cache, Firebase, utils, images)
```

## External dependencies (not bundled — configured per deployment)

| Dep | Where | How to swap |
|---|---|---|
| Firebase SDK | CDN `https://www.gstatic.com/firebasejs/10.14.1/...` | None — version pinned |
| Lucide icons | CDN `https://unpkg.com/lucide@0.294.0/...` | None — version pinned |
| **Cloudflare Worker proxy** | `https://chatomni-proxy.nhijudyshop.workers.dev` | Grep `chatomni-proxy.nhijudyshop.workers.dev` and replace with your Worker URL |
| **Render API server** | `https://n2store-fallback.onrender.com` | Worker handles all backend routing — just point the Worker at your Render |
| Firebase project | Configured in `shared/js/firebase-config.js` | Edit that file with your Firebase project config |

## Quick start

```bash
# 1. Copy this folder anywhere
cp -R web2-bundle/ ~/my-new-site/

# 2. Serve statically (any static host works)
cd ~/my-new-site
python3 -m http.server 8000
# → open http://localhost:8000/
```

## Deploy targets

### GitHub Pages

```bash
git init && git add . && git commit -m "init"
git remote add origin git@github.com:<user>/<repo>.git
git push -u origin main
# Settings → Pages → Branch: main → /
```

### Cloudflare Pages

Drag the folder into the Cloudflare Pages dashboard, or:

```bash
npx wrangler pages deploy web2-bundle --project-name=my-web2
```

### Netlify

```bash
npx netlify deploy --dir=web2-bundle --prod
```

## Customisation hooks

| Customise | File |
|---|---|
| Brand name "N2 Store" | grep `N2 Store` across `web2-shared/*.css` + sidebar JS |
| Worker URL | `web2-shared/*.js` + `*/js/*.js` — search for `chatomni-proxy` |
| Firebase project | `shared/js/firebase-config.js` |
| Default delivery zones + prices | `web2-shared/delivery-method-picker.js` `OPTIONS` array |

## Backend pre-requisites

The bundled UI talks to a Cloudflare Worker which in turn proxies to a
Render-hosted Express API + Postgres. To deploy your own backend:

1. Fork [render.com/](https://github.com/<your-fork>/render.com) → deploy on Render
2. Fork [cloudflare-worker/](https://github.com/<your-fork>/cloudflare-worker) → deploy on CF Workers, pointing it at your Render service
3. Update the Worker URL in this bundle (grep + replace)

See [docs/web2-packaging.md](../../docs/web2-packaging.md) in the source repo
for the full inventory + dependency graph.
README

# Print summary
FILE_COUNT=$(find "$ROOT/$OUT_DIR" -type f | wc -l | tr -d ' ')
BUNDLE_SIZE=$(du -sh "$ROOT/$OUT_DIR" | awk '{print $1}')
echo
echo "[pack-web2] ✓ Done."
echo "[pack-web2]   Bundle  : $ROOT/$OUT_DIR"
echo "[pack-web2]   Files   : $FILE_COUNT"
echo "[pack-web2]   Size    : $BUNDLE_SIZE"
echo
echo "[pack-web2] Quick preview:"
echo "[pack-web2]   cd $OUT_DIR && python3 -m http.server 8090"
echo "[pack-web2]   open http://localhost:8090/"
